/*  */
package fr.inria.diverse.mobileprivacyprofiler.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Collection;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import fr.inria.diverse.mobileprivacyprofiler.datamodel.associations.DetectedWifi_AccessPoint;
// Start of user code additional import for BatteryUsage
// End of user code

/** 
  * https://developer.android.com/training/monitoring-device-state/battery-monitoring.html 
  */ 
@DatabaseTable(tableName = "batteryUsage")
public class BatteryUsage {

	public static Log log = LogFactory.getLog(BatteryUsage.class);

	public static final String XML_BATTERYUSAGE = "BATTERYUSAGE";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_DATE = "date";
	public static final String XML_ATT_LEVEL = "level";
	public static final String XML_ATT_ISUSBPLUGGED = "isUsbPlugged";
	public static final String XML_ATT_ISACCPLUGGED = "isAccPlugged";
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	

	@DatabaseField
	protected java.lang.String date;

	@DatabaseField
	protected int level;

	@DatabaseField
	protected int isUsbPlugged;

	@DatabaseField
	protected int isAccPlugged;
	

	// Start of user code BatteryUsage additional user properties
	// End of user code
	
	public BatteryUsage() {} // needed by ormlite
	public BatteryUsage(java.lang.String date, int level, int isUsbPlugged, int isAccPlugged) {
		super();
		this.date = date;
		this.level = level;
		this.isUsbPlugged = isUsbPlugged;
		this.isAccPlugged = isAccPlugged;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}

	public java.lang.String getDate() {
		return this.date;
	}
	public void setDate(java.lang.String date) {
		this.date = date;
	}
	public int getLevel() {
		return this.level;
	}
	public void setLevel(int level) {
		this.level = level;
	}
	public int getIsUsbPlugged() {
		return this.isUsbPlugged;
	}
	public void setIsUsbPlugged(int isUsbPlugged) {
		this.isUsbPlugged = isUsbPlugged;
	}
	public int getIsAccPlugged() {
		return this.isAccPlugged;
	}
	public void setIsAccPlugged(int isAccPlugged) {
		this.isAccPlugged = isAccPlugged;
	}




	public String toXML(String indent, MobilePrivacyProfilerDBHelper contextDB){
		StringBuilder sb = new StringBuilder();
		sb.append(indent+"<");
    	sb.append(XML_BATTERYUSAGE);
		sb.append(" "+XML_ATT_ID+"=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_DATE);
    	sb.append("=\"");
		sb.append(StringEscapeUtils.escapeXml(this.date));
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_LEVEL);
    	sb.append("=\"");
		sb.append(this.level);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_ISUSBPLUGGED);
    	sb.append("=\"");
		sb.append(this.isUsbPlugged);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_ISACCPLUGGED);
    	sb.append("=\"");
		sb.append(this.isAccPlugged);
    	sb.append("\" ");
    	sb.append(">");


		// TODO deal with other case

		sb.append("</"+XML_BATTERYUSAGE+">");
		return sb.toString();
	}
}
