/*  */
package fr.inria.diverse.mobileprivacyprofiler.datamodel.associations;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.sql.SQLException;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import fr.inria.diverse.mobileprivacyprofiler.datamodel.*;

/** 
  *  
  */ 
@DatabaseTable(tableName = "gSMCell_NeighboringCellHistory")
public class GSMCell_NeighboringCellHistory {
 
	public static Log log = LogFactory.getLog(GSMCell_NeighboringCellHistory.class);

	
	public final static String GSMCELL_ID_FIELD_NAME = "GSMCell_id";
	public final static String NEIGHBORINGCELLHISTORY_ID_FIELD_NAME = "NeighboringCellHistory_id";

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	
	// This is a foreign object which just stores the id from the User object in this table.
	@DatabaseField(foreign = true, columnName = GSMCELL_ID_FIELD_NAME)
	GSMCell gSMCell;

	// This is a foreign object which just stores the id from the Post object in this table.
	@DatabaseField(foreign = true, columnName = NEIGHBORINGCELLHISTORY_ID_FIELD_NAME)
	NeighboringCellHistory neighboringCellHistory;

	/**
     * dbHelper used to autorefresh values and doing queries
     * must be set other wise most getter will return proxy that will need to be refreshed
	 */
	protected MobilePrivacyProfilerDBHelper _contextDB = null;

	/**
	 * object created from DB may need to be updated from the DB for being fully navigable
	 */
	public boolean _gSMCell_mayNeedDBRefresh = true;
	public boolean _neighboringCellHistory_mayNeedDBRefresh = true;

	GSMCell_NeighboringCellHistory() {
		// for ormlite
	}

	public GSMCell_NeighboringCellHistory(GSMCell gSMCell, NeighboringCellHistory neighboringCellHistory) {
		this.gSMCell = gSMCell;
		this.neighboringCellHistory = neighboringCellHistory;
	}

	/** accessors for Left part */  
	public GSMCell getGSMCell() {
		try {
			if(_gSMCell_mayNeedDBRefresh && _contextDB != null){
				_contextDB.gSMCellDao.refresh(this.gSMCell);
				this.gSMCell.setContextDB(_contextDB);
				_gSMCell_mayNeedDBRefresh = false;
			}
		} catch (SQLException e) {
			log.error(e.getMessage(),e);
		}
		if(_contextDB==null && this.gSMCell == null){
			log.warn("GSMCell_NeighboringCellHistory may not be properly refreshed from DB (_id="+_id+")");
		}
		return this.gSMCell;
	}
	public void setGSMCell(GSMCell gSMCell) {
		this.gSMCell = gSMCell;
	}

	/** accessors for Right part */ 
	public NeighboringCellHistory getNeighboringCellHistory() {
		try {
			if(_neighboringCellHistory_mayNeedDBRefresh && _contextDB != null){
				_contextDB.neighboringCellHistoryDao.refresh(this.neighboringCellHistory);
				this.neighboringCellHistory.setContextDB(_contextDB);
				_neighboringCellHistory_mayNeedDBRefresh = false;
			}
		} catch (SQLException e) {
			log.error(e.getMessage(),e);
		}
		if(_contextDB==null && this.neighboringCellHistory == null){
			log.warn("GSMCell_NeighboringCellHistory may not be properly refreshed from DB (_id="+_id+")");
		}
		return this.neighboringCellHistory;
	}
	public void setNeighboringCellHistory(NeighboringCellHistory neighboringCellHistory) {
		this.neighboringCellHistory = neighboringCellHistory;
	}


	public MobilePrivacyProfilerDBHelper getContextDB(){
		return _contextDB;
	}
	public void setContextDB(MobilePrivacyProfilerDBHelper contextDB){
		this._contextDB = contextDB;
	}
}
